### ISSUE TITLE
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

### ISSUE THREAD

**Issue by WesLee88524** [dvlab-research/ECCV22-P3AFormer-Tracking-Objects-as-Pixel-wise-Distributions#7]
Hi,Zelin!
I get some problems when I run the "sh configs/standard/v100_mot17_coco.sh " which remind me "ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'".
Then I find the answer at https://github.com/fundamentalvision/Deformable-DETR/issues/68.
I change my directory to "models/ops/" and run "sh make.sh",it  accurs some error:

`.conda/envs/torch1.9/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:115.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 47, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel`

I test on linux servers with v100.

Have u ever encountered this problem before?

**Comment by sjtuytc** [comment]
I didn't meet the problems before.
You can first look at these issues: https://github.com/fundamentalvision/Deformable-DETR/issues?q=is%3Aissue+cuda+is+not+available+is%3Aclosed
https://github.com/fundamentalvision/Deformable-DETR/issues/112
https://github.com/fundamentalvision/Deformable-DETR/issues/88
It seems that you cannot find CUDA library on your server. You can check via 
`nvcc --version` to see if your CUDA library is added to the LD_LIBRARY_PATH, where the extensions normally find the CUDA.
